services:
  bot:
    environment:
      - TZ=Europe/Paris
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    build: .
    env_file: .env
    restart: always
    volumes:
      - .:/app